#!/bin/zsh

export GOPATH=$HOME
case ${OSTYPE} in
  darwin*)
    export GOOS=darwin
    ;;
  linux*)
    export GOOS=linux
esac
case $(uname -m) in
  i686*)
    export GOARCH=386
    ;;
  x86_64*)
    export GOARCH=amd64
    ;;
esac
export PATH=$PATH:$GOPATH/bin
