#!/bin/zsh
# refs http://blog.uu59.org/2014-01-06-fast-rbenv.html

path=(
  $HOME/.phpenv/bin(N-/)
  $path
)

if [ $+commands[phpenv] -ne 0 ]; then
  phpenv_init() {
    export PHPENV_SHELL=zsh
    source "$HOME/.phpenv/completions/rbenv.zsh"
    rbenv() {
      local command
      command="$1"
      if [ "$#" -gt 0 ]; then
        shift
      fi

      case "$command" in
        rehash|shell)
          eval "`rbenv "sh-$command" "$@"`";;
        *)
          command rbenv "$command" "$@";;
      esac
    }
    path=($HOME/.phpenv/shims $path)
  }
  phpenv_init
  unfunction phpenv_init
fi

