#!/bin/zsh
# refs http://blog.uu59.org/2014-01-06-fast-rbenv.html

path=(
  $HOME/.rbenv/bin(N-/)
  $path
)

if [ $+commands[rbenv] -ne 0 ]; then
  rbenv_init() {
    export RBENV_SHELL=zsh
    source "$HOME/.rbenv/completions/rbenv.zsh"
    rbenv() {
      local command
      command="$1"
      if [ "$#" -gt 0 ]; then
        shift
      fi

      case "$command" in
        rehash|shell)
          eval "`rbenv "sh-$command" "$@"`";;
        *)
          command rbenv "$command" "$@";;
      esac
    }
    path=($HOME/.rbenv/shims $path)
  }
  rbenv_init
  unfunction rbenv_init
fi
